language: cpp
dist: trusty
sudo: required
cache: ccache
install: travis/install_deps.sh
script: travis/compile.sh
env:
  matrix:
    - PLATFORM="native_static"
    - PLATFORM="native_dyn"
    - PLATFORM="win32_static"
    - PLATFORM="win32_dyn"
